// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro.DAL;

namespace Registro.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200521113823_First-Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Registro.Models.Persona", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(11);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.HasKey("PersonaID");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaID = 1,
                            Cedula = "05600345926",
                            Direccion = "Calle Roberto Acevedo #34",
                            FechaDeNacimiento = new DateTime(2020, 5, 21, 7, 38, 23, 222, DateTimeKind.Local).AddTicks(6904),
                            Nombres = "Juan Alberto",
                            Telefono = "8292655182"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
